FROM mcr.microsoft.com/dotnet/framework/sdk:3.5

ADD Framework/ inetpub/wwwroot/BATA/Framework
ADD libs/ inetpub/wwwroot/BATA/libs
ADD Project/ inetpub/wwwroot/BATA/Project
ADD run.bat run.bat

CMD ["run.bat"]